config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root 'workflow_templates#index'
  get 'access/menu'
  get 'access/login'
  get 'states/new'
  get 'states/index'
  get 'states/edit'
  get 'states/delete'
  get 'state/new'
  get 'state/index'
  get 'state/edit'
  get 'state/delete'
  post 'access/attempt_login'
  get 'access/logout'
  get 'home', :to => 'access#home'
  #get 'workflow_templates/index'
  #get 'workflow_templates/show'
  #get 'workflow_templates/new'
  #get 'workflow_templates/create'
  #get 'workflow_templates/edit'
  #get 'workflow_templates/delete'
  #get 'workflow_templates/destroy'
  get 'workflow_templates/addedge'
  post 'workflow_templates/addedge'
  get 'workflow_templates/removeedge'
  post 'workflow_templates/removeedge'
  get 'demo/index'

  resources :workflow_templates do
    member do
      get :delete
    end
  end

  resources :states do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout, :home]

  def home
  end

  def login
  end

  def attempt_login
    if params[:uname].present? && params[:upwd].present?
      found_user = AdminUser.where(:username => params[:uname]).first
      if found_user
        authorized_user = found_user.authenticate(params[:upwd])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      puts "Login successfully"
      flash[:notice] = "Welcome #{authorized_user.last_name}, #{authorized_user.first_name}!"
      #UserMailer.welcome_email.deliver_later
      MailWorker.perform_async(authorized_user)
      redirect_to(workflow_templates_path)
    else
      puts "incorrect username/password."
      flash[:notice] = "Incorrect username/password."
      render('login')
    end
  end

  def logout
    session[:user_id] = nil
    puts "logged out successfully."
    flash[:notice] = "Logged out!"
    redirect_to(home_path)
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/home.html.erb
<% page_title = "menu" %>

<%= form_tag( access_login_path, :method => :get ) do %>
  
  <div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
      <div class="jumbotron">
        <h3>Workflow system</h3><br>
      
        <div class="form buttons">
            <%= submit_tag "Login", class: "btn btn-primary" %>
        </div><br>
      </div>
    </div>

    <div class="col-md-4">
    </div>
  </div>
<% end %>

app/views/access/login.html.erb
<% page_title = "login" %>

<%= form_tag( access_attempt_login_path, :method => :post ) do %>
  
  <div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= text_field_tag :uname, params[:uname], placeholder: "Username", class: "form-control" %>
      </div><br>

      <div class="form-group">
        <%= password_field_tag :upwd, params[:upwd], placeholder: "Password", class: "form-control" %>
      </div><br>

      <div class="form buttons">
        <%= submit_tag "Log In", class: "btn btn-primary" %>
      </div><br>
    </div>

    <div class="col-md-4">
    </div>
  </div>
<% end %>

app/views/access/menu.html.erb
<% page_title = "menu" %>

<%= form_tag( access_login_path, :method => :get ) do %>
  
  <div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
      <div class="jumbotron">
        <h3>Workflow system</h3><br>
      
        <div class="form buttons">
            <%= submit_tag "Login", class: "btn btn-primary" %>
        </div><br>
      </div>
    </div>

    <div class="col-md-4">
    </div>
  </div>
<% end %>