config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root 'workflow_templates#index'
  get 'access/menu'
  get 'access/login'
  get 'states/new'
  get 'states/index'
  get 'states/edit'
  get 'states/delete'
  get 'state/new'
  get 'state/index'
  get 'state/edit'
  get 'state/delete'
  post 'access/attempt_login'
  get 'access/logout'
  get 'home', :to => 'access#home'
  #get 'workflow_templates/index'
  #get 'workflow_templates/show'
  #get 'workflow_templates/new'
  #get 'workflow_templates/create'
  #get 'workflow_templates/edit'
  #get 'workflow_templates/delete'
  #get 'workflow_templates/destroy'
  get 'workflow_templates/addedge'
  post 'workflow_templates/addedge'
  get 'workflow_templates/removeedge'
  post 'workflow_templates/removeedge'
  get 'demo/index'

  resources :workflow_templates do
    member do
      get :delete
    end
  end

  resources :states do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workflow_template.rb
class WorkflowTemplate < ApplicationRecord
    has_many :transitions, { :foreign_key => "workflow_id" }

    #named scopes
    scope :newest_first, lambda { order("created_at DESC")}
end

app/controllers/workflow_templates_controller.rb
require 'rgl/adjacency'
require 'rgl/dot'
require 'fileutils'

class WorkflowTemplatesController < ApplicationController

  before_action :confirm_logged_in
  
  @workflow_name
  
  def index
    @workflows = WorkflowTemplate.newest_first
  end

  def show
    _wid = params[:id]
    @workflows = WorkflowTemplate.find(_wid)
    #@dg = RGL::DirectedAdjacencyGraph["ONE","TWO" ,"TWO","THREE" ,"THREE","FOUR", "FOUR","FIVE", "SIX","FOUR", "ONE","SIX", "NINE","TEN"]
    @dag = RGL::DirectedAdjacencyGraph[];

    @workflows.transitions.each do |e|
      @dag.add_edge(e.from_state.name, e.to_state.name)
    end

    @dag.write_to_graphic_file('jpg')
    FileUtils.mv('./graph.jpg', './app/assets/images/graph.jpg');
  end

  def new
    @wf = WorkflowTemplate.new()
  end

  def create
    _name = params[:workflow_template][:name]
    _desc = params[:workflow_template][:desc]
  
    @wf = WorkflowTemplate.new({name: _name, initial_state: "root", desc: _desc})
  
    begin
      if @wf.save
        render('addedge')
      else
        puts "Workflow already exists!"
        render("new")
      end
    rescue
      puts "Caught error..."
    end
  end

  def edit
    @wid = params[:id]

    begin
      @wf = WorkflowTemplate.find(@wid)
      puts "Found workflow"
      @dg = RGL::DirectedAdjacencyGraph[];
      @wf.transitions.each do |e|
        @dg.add_edge(e.from_state.name, e.to_state.name)
      end
      @dg.write_to_graphic_file('jpg')
      FileUtils.mv('./graph.jpg', './app/assets/images/graph.jpg');
      render("removeedge")
    rescue
      puts "No workflow exists."
    end
  end

  def update
  end

  def delete
    begin
      @workflow = WorkflowTemplate.find_by_id(params[:id])
      if @workflow == nil
        puts "nil object."
      end
    rescue
      puts "caught error."
    end
  end

  def destroy
    if params[:commit] == "Ok"
      @wid = params[:id]
      puts "ID: #{params[:id]}"
      begin
        @wf = WorkflowTemplate.find(@wid)
        if(@wf != nil)
          puts "Found workflow"
          @wf.destroy
          redirect_to action: "index"
        end
      rescue
        puts "caught error."
      end
    else
      redirect_to action: "index"
    end
  end

  def addedge
    @wid = params[:wid]
    @from = params[:vfrom]
    @to = params[:vto]
    @trname = params[:vname]
    @trdesc = params[:vdesc]
    @key1 = params[:key1]
    @value1 = params[:value1]
    @key2 = params[:key2]
    @value2 = params[:value2]

    if @dg == nil
      @dg = RGL::DirectedAdjacencyGraph[];
    end
    if @from != nil && @to != nil
      begin
        @fst = State.find_by!(name: "#{@from}")
        puts "fst id: #{@fst.id}"
        @tst = State.find_by!(name: "#{@to}")
        puts "tst id: #{@tst.id}"
      rescue
        puts "caught error."
      end

      @dg.add_edge(@from, @to)

      begin
        @wf = WorkflowTemplate.find(@wid)
        puts "found workflow"
      rescue
        puts "No workflow exists."
      end

      @wf.transitions.each do |e|
        @dg.add_edge(e.from_state.name, e.to_state.name)
      end

      @dg.write_to_graphic_file('jpg')
      FileUtils.mv('./graph.jpg', './app/assets/images/graph.jpg');

      begin
        @tr = Transition.new(workflow_id: "#{@wf.id}", name: "#{@trname}", from_state_id: "#{@fst.id}", to_state_id: "#{@tst.id}", desc: "#{@trdesc}")
        @tr.save
      rescue
        puts "DB query failed for tr."
      end

      begin
        if @key1 != nil && @value1 != nil
          @cr1 = Criterium.new(transition_id: "#{@tr.id}", criteria_type: 0, key: "#{@key1}", value: "#{@value1}")
          @cr1.save
        end
      rescue
        puts "DB query failed for cr-a."
      end

      begin
        if @key2 != nil && @value2 != nil
          @cr2 = Criterium.new(transition_id: "#{@tr.id}", criteria_type: 0, key: "#{@key2}", value: "#{@value2}")
          @cr2.save
        end
      rescue
        puts "DB query failed for cr-b."
      end
    end
  end

  def removeedge
    @wid = params[:wid]
    @from = params[:vfrom]
    @to = params[:vto]
    if @dg == nil
      @dg = RGL::DirectedAdjacencyGraph[];
    end
    if @from != nil && @to != nil
      begin
        @fst = State.find_by!(name: "#{@from}")
        puts "fst id: #{@fst.id}"
      rescue
        puts "State #{@from} not exists in DB."
      end
      begin
        @tst = State.find_by!(name: "#{@to}")
        puts "tst id: #{@tst.id}"
      rescue
        puts "State #{@to} not exists in DB."
      end

      begin
        @tr = Transition.find_by!(workflow_id: "#{@wid}", from_state_id: "#{@fst.id}", to_state_id: "#{@tst.id}")
        if(@tr == nil)
          puts "No such transition"
        else
          @tr.destroy
        end
      rescue
        puts "DB query failed."
      end
      begin
        @wf = WorkflowTemplate.find(@wid)
        puts "found workflow"
      rescue
        puts "No workflow exists."
      end

      @wf.transitions.each do |e|
        @dg.add_edge(e.from_state.name, e.to_state.name)
      end

      @dg.write_to_graphic_file('jpg')
      FileUtils.mv('./graph.jpg', './app/assets/images/graph.jpg');
    
      puts " "
      puts "workflow_id: #{@wf.id}"
      puts "name: anyname"
      puts "from_state_id: #{@fst.id}"
      puts "to_state_id: #{@tst.id}"
      puts " "
      
    end
  end
end

app/helpers/workflow_templates_helper.rb
module WorkflowTemplatesHelper
end

app/views/workflow_templates/addedge.html.erb
<br><h3>Add Transition</h3><br>

<%= form_tag( :action => 'addedge', :wid => "#{@wf.id}", :method => "GET" ) do %>
  
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= text_field_tag :vname, params[:vname], placeholder: "Name", class: "form-control" %>
      </div><br>

      <div class="form-group">  
        <!--%= text_field_tag :vfrom, params[:vfrom], placeholder: "From", class: "form-control" %-->
        <%= select_tag "vfrom", options_from_collection_for_select(State.order("name ASC"), :name, :name), prompt: "From", class: "form-control" %>
      </div><br>
    
      <div class="form-group">
        <!--%= text_field_tag :vto, params[:vto], placeholder: "To", class: "form-control" %-->
        <%= select_tag "vto", options_from_collection_for_select(State.order("name ASC"), :name, :name), prompt: "To", class: "form-control" %>
      </div><br>

      <div class="form-group">
        <%= text_area_tag :vdesc, params[:vdesc], placeholder: "Description", class: "form-control", rows: "4" %>
      </div><br>

      <!--div class="form-group" id="additem">
      </div><br-->

      <div class="form-group">
        <%= text_field_tag :key1, params[:key1], placeholder: "Key", class: "form-control" %>
        <%= text_field_tag :value1, params[:value1], placeholder: "Value", class: "form-control" %><br>

        <%= text_field_tag :key2, params[:key2], placeholder: "Key", class: "form-control" %>
        <%= text_field_tag :value2, params[:value2], placeholder: "Value", class: "form-control" %>
      </div><br>

      <div class="form buttons">
        <!--input type="button" value="+", id="addattr", class="btn btn-primary"-->
        <%= submit_tag "Add", class: "btn btn-primary" %>
      </div><br>
    </div> 
    <div class="col-md-4">
    </div>
    <div class="col-md-5">
      <div class="form-group">
        <% if @from != nil && @to != nil %>
          <%= image_tag('graph.jpg', class:"img-fluid", alt:"workflow image") %>
        <% end %>
      </div>
    </div>
  </div>
       
<% end %>

app/views/workflow_templates/delete.html.erb
<!--%= link_to("<< Back TO List", workflow_templates_path, :class => "back-link") %-->

<div class="jumbotron">

    <%= form_for(@workflow, :method => 'delete') do |f| %>
        <h3>Are you sure want to permanently delete this workflow?</h3>

        <br/>
        <p class="label label-info"><%= f.object.name %></p>
        <br/><br/>
        <%= f.submit "Back", style: "margin:5px", class: "btn pull-right" %>
        <%= f.submit "Ok", style: "margin:5px", class: "btn pull-right" %>
    <% end %>

</div>

app/views/workflow_templates/index.html.erb
    <br><h3>List of Workflows</h3><br>
    
    <table class="table table-hover" summary="WorkflowTemplate list">
        <thead>
            <tr>
                <th scope="col"><h4>Name</h4></th>
                <th scope="col"><h4>Action</h4></th>
            </tr>
        </thead>
        <tbody>
            <% @workflows.each do |workflow| %>
            <tr>
                <td><h5><%= workflow.name %></h5></td>
                <td>
                    <%= link_to("Show", workflow_template_path(workflow)) %>
                    <%= link_to("Edit", {:controller => "workflow_templates", :action => "edit", :id => "#{workflow.id}" }) %>
                    <%= link_to("Delete", delete_workflow_template_path(workflow)) %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>

app/views/workflow_templates/new.html.erb
<br>

<h3>Create Workflow</h3><br><br><br>

<%= form_for(@wf) do |f| %>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div><br>
  <div class="form-group">
    <%= f.text_area :desc, class: "form-control", placeholder: "Enter description", rows: "4" %>
  </div><br>
  <div class="form buttons">
    <%= f.submit "Create", class: "btn btn-primary"%>
  </div>
  </div>
  <div class="col-md-3">
  </div>
<% end %>
<br><br><br><br> 
<br><br><br><br> 
<br><br><br><br> 
<br><br><br><br>

app/views/workflow_templates/removeedge.html.erb
<br><h3>Remove Transition</h3><br>

<%= form_tag( :action => 'removeedge', :wid => "#{@wid}", :method => "GET" ) do %>
  
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">  
        <%= text_field_tag :vfrom, params[:vfrom], placeholder: "From", class: "form-control" %>
      </div><br>
    
      <div class="form-group">
        <%= text_field_tag :vto, params[:vto], placeholder: "To", class: "form-control" %>
      </div><br>

      <div class="form buttons">
        <%= submit_tag "Remove", class: "btn btn-primary" %>
      </div><br>
    </div> 
    <div class="col-md-4">
    </div>
    <div class="col-md-5">
      <div class="form-group">
        <%= image_tag('graph.jpg', class:"img-fluid", alt:"workflow image") %>
      </div>
    </div>
  </div>
       
<% end %>

app/views/workflow_templates/show.html.erb
<br><h3>Workflow</h3><br>

<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <%= image_tag('graph.jpg', size: '600x600', alt: 'workflow') %>
    </div>
    <div class="col-md-3">
    </div>
</div>