config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root 'workflow_templates#index'
  get 'access/menu'
  get 'access/login'
  get 'states/new'
  get 'states/index'
  get 'states/edit'
  get 'states/delete'
  get 'state/new'
  get 'state/index'
  get 'state/edit'
  get 'state/delete'
  post 'access/attempt_login'
  get 'access/logout'
  get 'home', :to => 'access#home'
  #get 'workflow_templates/index'
  #get 'workflow_templates/show'
  #get 'workflow_templates/new'
  #get 'workflow_templates/create'
  #get 'workflow_templates/edit'
  #get 'workflow_templates/delete'
  #get 'workflow_templates/destroy'
  get 'workflow_templates/addedge'
  post 'workflow_templates/addedge'
  get 'workflow_templates/removeedge'
  post 'workflow_templates/removeedge'
  get 'demo/index'

  resources :workflow_templates do
    member do
      get :delete
    end
  end

  resources :states do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="jumbotron">
<footer class="page-footer font-small stylish-color-dark pt-4">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© Copyright 2018
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Home", workflow_templates_path, :class => "navbar-brand") %>
    </div>

    <ul class="nav navbar-nav">
      <li class="dropdown">
      <a href="#" class="navbar-brand" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">New 
      <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to("Workflow", new_workflow_template_path) %></li>
          <li><%= link_to("State", new_state_path) %></li>
        </ul>
      </li>
    </ul>

    <div class="navbar-header pull-right">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if session[:user_id] != nil %>
      <%= link_to("Log out", access_logout_path, :class => "navbar-brand") %>
      <% end %>
    </div-->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workflow" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Workflow" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <script src="/jquery-3.3.1.min.js"></script>
    <script src="/bootstrap.min.js"></script>
    <script src="/custom.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render partial: "layouts/navbar" %>
    </header>

    <% if !flash[:notice].blank? %>
      <div class = "jumbotron">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>

    <%= render partial: "layouts/footer" %>
  </body>
</html>